# -*- coding: utf-8 -*-

CORE_MODEL_NAME = 'CoreModel'

INNER_INSERT_FIELDS = ''
INNER_UPDATE_FIELDS = ''

MYSQL_DATABASE = 'orm'
MYSQL_HOST = '192.168.36.3'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASSWD = '111111'
MYSQL_CONNECTION_TIMEOUT = 24*60*60

FIELD_TYPE_STRING = 'varchar(255)'
FIELD_TYPE_INT = 'bigint'
FIELD_TYPE_TIME = ''

